#!/usr/bin/env python3
"""
One-shot migration: make the twenty subject columns in rule-16-1-tracker.csv derived
output equal to `reached` in subject-treatment.csv.

This is the step the codebook committed to:

    "rule-16-1-tracker.csv remains the public order-level summary, and its twenty subject
     columns become derived output equal to `reached`, regenerated by build.py."

It is a one-shot script rather than a build step on purpose. build.py writes index.html;
letting it also write the data file would risk clobbering hand-maintained columns on an
unrelated run. Instead build.py ASSERTS the two agree and fails if they drift, so the
guarantee is the same and the blast radius is not.

    python3 migrate_subject_columns.py --dry-run    # print the diff, change nothing
    python3 migrate_subject_columns.py              # write, after printing the diff

Mapping, per the codebook's coding vocabulary:

    reached TRUE   ->  YES
    reached FALSE  ->  NOT_ADDRESSED     (silence is never coded NO)

Rows with no subject-level coding are left exactly as they are. Today that is MDL 3176
(no qualifying order yet) and MDL 3187 (blocked), both PENDING across all twenty.

The file is rewritten with csv.DictWriter's default CRLF terminator, which reproduces the
existing file byte for byte when nothing changes. Verified before first use.
"""
import csv, io, sys

ORDER_CSV = "rule-16-1-tracker.csv"
SUBJECT_CSV = "subject-treatment.csv"
SUBJECTS = [
    "b2a_leadership", "b2a_timing", "b2a_structure", "b2a_selection_procedure",
    "b2a_periodic_review", "b2a_responsibilities", "b2a_communication",
    "b2a_nonleadership_limits", "b2a_compensation", "b2b_vacate_modify",
    "b2c_conference_schedule", "b2d_direct_filing", "b2e_related_actions",
    "b3a_consolidated_pleadings", "b3b_factual_basis_exchange", "b3c_discovery",
    "b3d_pretrial_motions", "b3e_settlement_facilitation", "b3f_magistrate_master",
    "b3g_principal_issues",
]


def derived():
    """{mdl_no: {subject_id: 'YES' | 'NOT_ADDRESSED'}} for every coded order."""
    out = {}
    for r in csv.DictReader(open(SUBJECT_CSV)):
        if not r["reached"].strip():
            continue
        out.setdefault(r["mdl_no"], {})[r["subject_id"]] = (
            "YES" if r["reached"].strip().upper() == "TRUE" else "NOT_ADDRESSED")
    return out


def main():
    dry = "--dry-run" in sys.argv
    want = derived()
    raw = open(ORDER_CSV, newline="").read()
    rows = list(csv.DictReader(io.StringIO(raw)))
    header = list(rows[0].keys())

    changes, untouched = [], []
    for r in rows:
        mdl = r["mdl_no"]
        if mdl not in want:
            untouched.append(mdl)
            continue
        missing = [s for s in SUBJECTS if s not in want[mdl]]
        if missing:
            sys.exit(f"MDL {mdl}: subject-level table is missing {len(missing)} subject(s); "
                     f"refusing to migrate a partially coded order")
        for s in SUBJECTS:
            old, new = r[s].strip(), want[mdl][s]
            if old != new:
                changes.append((mdl, s, old, new))
            r[s] = new

    print(f"{len(want)} coded orders x {len(SUBJECTS)} subjects = "
          f"{len(want) * len(SUBJECTS)} cells considered")
    print(f"left untouched (no subject-level coding): {', '.join(untouched) or 'none'}")
    print(f"\n{len(changes)} cell(s) change:\n")
    by_kind = {}
    for mdl, s, old, new in changes:
        by_kind.setdefault((old, new), []).append((mdl, s))
    for (old, new), items in sorted(by_kind.items(), key=lambda kv: -len(kv[1])):
        print(f"  {old:<15} -> {new:<15} ({len(items)})")
        for mdl, s in items:
            print(f"        MDL {mdl}  {s}")

    if dry:
        print("\n--dry-run: nothing written")
        return

    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=header)      # default CRLF, matches the file
    w.writeheader()
    w.writerows(rows)
    open(ORDER_CSV, "w", newline="").write(buf.getvalue())
    print(f"\nwrote {ORDER_CSV}")


if __name__ == "__main__":
    main()
